spring:
  application:
    name: brambling-note-note
  config:
    import: "consul:"
  cloud:
    consul:
      discovery:
        health-check-path: /health
      config:
        format: yaml
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      auto-offset-reset: earliest
